
name: Tests on platforms

on:
  pull_request:
    branches:
    - master

jobs:
  redis:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Start containers
      run: docker-compose -f "docker-compose.yaml" up -d --build redis
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install pytest
    - name: Run tests
      run: pytest -m redis tests/
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yaml" down
  kafka:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Start containers
      run: docker-compose -f "docker-compose.yaml" up -d --build kafka
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install pytest
    - name: Run tests
      run: pytest -m kafka tests/
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yaml" down
  postgres:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Start containers
      run: docker-compose -f "docker-compose.yaml" up -d --build postgres
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install pytest
    - name: Run tests
      run: pytest -m postgres tests/
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yaml" down